package com.example.restdemo;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class RestDemoApplicationTests {



	@Test
	void contextLoads() {
	}

}

/*
	TODO 3

	Run the test generated by Spring Initializr and make sure it passes (green).

	When you clone/pull/import a project, start your work by:
	- running the existing tests.
	When you switch Git branch, before running the tests, reload the Maven/Gradle project.
 */

/*
	TODO 4: A short discussion within your team (write down your thoughts/ questions):

	What is the role of:
	- @SpringBootTest
	- @Test

	We can see that the test method is empty - is it okay in this case scenario?

 */

/*
	TODO 5: checkout the next branch (2_create-the-model)
 */